import AcumenImage from "../assets/HomepageAcumen.png"
// import {FaArrowRight} from "react-icons/fa"
import AnalysedDashboard from "../assets/analysedData.png"

const AcumenIntelligence = () => {

  return (
    <section  className="min-h-screen bg-gradient-to-br from-emerald-950 via-black to-slate-950 relative overflow-hidden">
    <div className="absolute top-20 left-10 w-80 h-80 bg-emerald-500/20 blur-[130px] rounded-full"></div>
    <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-emerald-400/10 blur-[150px] rounded-full"></div>
    <div className=" py-5 text-white leading-relaxed">
        <div className="items-center gap-6 bg-white/5 border border-white/10 rounded-xl p-5 ml-2 hover:border-emerald-400 transition">
        <h3 className="text-2xl font-bold">Acumen Intelligence</h3>
        <p>Acumen Intelligence is a full-stack web application integrated with a Large Language Model (LLM) to deliver intelligent customer conversation analytics. The platform enables businesses to analyze customer interactions and identify missed opportunities, recurring pain points, customer sentiment, and potential areas for growth. The insights generated by the LLM are presented through an intuitive and interactive dashboard, allowing businesses to quickly understand customer feedback, make data-driven decisions, and improve customer satisfaction and retention.</p>
        <br/>
        <p className="text-xl font-bold">Tech stack : </p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Frontend : React + vite</li>
          <li>Backend : Express</li>
          <li>Database : PostgreSQL</li>
        </ul>
        </div>
      </div>
      <button className="flex bg-green-500 w-40 rounded-2xl px-3 text-xl hover:bg-green-700 ml-2 justify-center">Live Demo</button>
      <div className=" py-5 text-white leading-relaxed">
        <div className="items-center gap-6 bg-white/5 border border-white/10 rounded-xl p-5 hover:border-emerald-400 transition">
        <img src={AcumenImage} alt="Acumen-Intelligence"></img>
        </div>

      </div>
      <div className=" py-5 text-white leading-relaxed">
        <div className="items-center gap-6 bg-white/5 border border-white/10 rounded-xl p-5 hover:border-emerald-400 transition">
        {/* //CHANGE IMAGE */}
        <img src={AnalysedDashboard} alt="Dashboard Preview"></img>
        </div>
        
      </div>
    </section>
  )
}

export default AcumenIntelligence
